### ISSUE TITLE
列表分页查询后，每次重建Fragment 后LiveData缓存的数据都重复添加到list

### ISSUE THREAD

**Issue by dalingge** [miaowmiaow/fragmject#11]
<img width="726" alt="WeChat094d63c6d20461f8a486027d1e1b78eb" src="https://user-images.githubusercontent.com/5687256/182534957-cecf4c27-de3f-4028-9439-5f9cfa05379c.png">

**Comment by miaowmiaow** [comment]
感谢反馈，麻烦描述下操作步骤或其他能帮助我定位问题的信息😁

**Comment by dalingge** [comment]
> 感谢反馈，麻烦描述下操作步骤或其他能帮助我定位问题的信息😁

首页列表进行分页查询后，点击进入详情页在返回首页，这个时候首页Fragment 重建后，ViewModel会重新请求上一次分页的页码，你首页的ArticleAdapter()是一个常量里面的list没有被清空，这个时候重复请求页码的数据就会重新添加进list里面

**Comment by miaowmiaow** [comment]
通过你的反馈，定位到问题是由 LiveData 粘性事件导致。目前想到两种解决方案：一是视图销毁时清除 LiveData 的数据，二是使用 SingleLiveEvent 。相关代码已经更新，如果你有更好的方案欢迎一起交流😁

**Comment by miaowmiaow** [comment]
> 
通过你的反馈，定位到问题是由 LiveData 粘性事件导致。目前想到两种解决方案：一是视图销毁时清除 LiveData 的数据，二是使用 SingleLiveEvent 。相关代码已经更新，如果你有更好的方案欢迎一起交流😁

**Comment by miaowmiaow** [comment]
> > 感谢反馈，麻烦描述下操作步骤或其他能帮助我定位问题的信息😁
> 
> 首页列表进行分页查询后，点击进入详情页在返回首页，这个时候首页Fragment 重建后，ViewModel会重新请求上一次分页的页码，你首页的ArticleAdapter()是一个常量里面的list没有被清空，这个时候重复请求页码的数据就会重新添加进list里面

通过你的反馈，定位到问题是由 LiveData 粘性事件导致。目前想到两种解决方案：一是视图销毁时清除 LiveData 的数据，二是使用 SingleLiveEvent 。相关代码已经更新，如果你有更好的方案欢迎一起交流😁
