### ISSUE TITLE
图片编辑器功能，插入文字后再旋转一定角度（比如90度），这个时候就点击不到文字sticker

### ISSUE THREAD

**Issue by spysoos** [miaowmiaow/fragmject#14]
图片编辑器功能，插入文字后再旋转一定角度（比如90度），这个时候就点击不到文字sticker。应该是没有坐标转换，希望作者能修正！

**Comment by miaowmiaow** [comment]
感谢反馈，该问题已修正，并且适配android13的权限管理😊
