### ISSUE TITLE
没人觉得app好卡吗

### ISSUE THREAD

**Issue by pangyu646182805** [miaowmiaow/fragmject#16]
compose性能问题吗

**Comment by miaowmiaow** [comment]
现阶段与原生view对比compose确实会给人卡顿的感觉，你可以切换到 release 进行构建会提升流畅度，我这边也会继续研究相关优化方面的知识
![20230809141657](https://github.com/miaowmiaow/fragmject/assets/13847718/a5acd16b-dd4e-43de-8252-c52c7e9d693a)

**Comment by miaowmiaow** [comment]
我建了个交流群，欢迎进来讨论关于android的任何问题，加群方式在readme末尾
