### ISSUE TITLE
大佬，可以把如下方法集成到 SystemHelper中吗

### ISSUE THREAD

**Issue by yuwaixingtian** [miaowmiaow/fragmject#17]
如题，不太清楚为什么com.example.miaow.base.utils.SystemHelper 这个类中的 Context.getVersionName 等方法在需要使用到 Context 的地方居然可以省略掉，我查找了整个项目没有发现 packageManager 首字母小写的其他类似 var，val的申明关键词，没想到作者您是写法居然可以使用。所以想知道下面提供的两个获取系统IP的方法能否集成进这个系统类中：
` //获取外网IP`
`suspend fun getPublicIP(): String {`
 `       val response: HttpResponse = client.get("https://api.ipify.org")`
`        var publicIP = try {`
`            response.bodyAsText()`
`        } catch (e: Exception) {`
`            e.printStackTrace()`
`            e.toString()`
`        }`
`        return publicIP`
`    }`

`//获取局域网IP`
`fun getIpAddress(context: Context): String {`
`    val wifiManager = context.getSystemService(Context.WIFI_SERVICE) as WifiManager`
`    val ip = Formatter.formatIpAddress(wifiManager.connectionInfo.ipAddress)`
`    return ip`
`}`
非常感谢大佬！麻烦啦～

**Comment by miaowmiaow** [comment]
`
//获取局域网IP
fun getIpAddress(context: Context): String {
    val wifiManager = context.getSystemService(Context.WIFI_SERVICE) as WifiManager
    val ip = Formatter.formatIpAddress(wifiManager.connectionInfo.ipAddress)
    return ip
}

//获取局域网IP（改造后）
fun Context.getIpAddress(): String {
    val wifiManager = getSystemService(Context.WIFI_SERVICE) as WifiManager
    val ip = Formatter.formatIpAddress(wifiManager.connectionInfo.ipAddress)
    return ip
}
`
你对比下代码就能发现区别，属于kotlin的语法糖之一

非Bug问题可以加群交流，写Issuse效率慢且容易让人误解

**Comment by yuwaixingtian** [comment]
> ` //获取局域网IP fun getIpAddress(context: Context): String { val wifiManager = context.getSystemService(Context.WIFI_SERVICE) as WifiManager val ip = Formatter.formatIpAddress(wifiManager.connectionInfo.ipAddress) return ip }
> 
> //获取局域网IP（改造后） fun Context.getIpAddress(): String { val wifiManager = getSystemService(Context.WIFI_SERVICE) as WifiManager val ip = Formatter.formatIpAddress(wifiManager.connectionInfo.ipAddress) return ip } ` 你对比下代码就能发现区别，属于kotlin的语法糖之一
> 
> 非Bug问题可以加群交流，写Issuse效率慢且容易让人误解

哈哈哈哈哈，懂了懂了，我就说怎么提交两天一直刷新没看见回复，谢谢大佬
