### ISSUE TITLE
大佬大佬，请教一下 WanViewModel 数据更新中的问题

### ISSUE THREAD

**Issue by yuwaixingtian** [miaowmiaow/fragmject#18]
大佬大佬，请问一下在 WanViewModel 类中如果想要更新的是数据库中的数据我应该怎么写会比较好呢，刚接触咱这个框架，虽然很好用但是还是在渐渐的探索中，我目前的做法是从该类的
`data class WanState(`
`    var isLoading: Boolean = false,`
`    var hotKeyResult: MutableList<HotKeyBean> = ArrayList(),`
 `   var treeResult: MutableList<TreeBean> = ArrayList(),`
 `   //新增的一个数据库数据`
 `   var newInfo: List<String> = ArrayList(),`
`)`
新增一个 newInfo 参数接受数组，接着模仿 getHotKeyList 方法一样写一个挂起函数为 getNewInfo 方法，然后去调用对应的和 HotKeyListBean 一样的数据集，不知道这样的方法是否合适，有些疑惑TvT

**Comment by miaowmiaow** [comment]
需要更新UI的写在UIState中，其它可以直接写在ViewModel中
`
class TestViewModel : ViewModel() {

    private var newInfo: MutableList<String> = ArrayList()
    
    fun updateInfo(info: List<String>){
        newInfo.addAll(info)
    }

}
`

非Bug问题可以加群交流，写Issuse效率慢且容易让人误解
