### ISSUE TITLE
运行master分支需要的as版本是什么?

### ISSUE THREAD

**Issue by wangjianxiang** [miaowmiaow/fragmject#19]
Android Studio Giraffe | 2022.3.1 Patch 3
Build #AI-223.8836.35.2231.11005911, built on October 26, 2023
Runtime version: 17.0.6+0-b2043.56-10027231 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 16
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    run.processes.with.pty=false
    ide.instant.shutdown=false

Non-Bundled Plugins:
    plantuml-parser (0.0.4)
    PlantUML integration (6.5.0-IJ2022.2)
    idea.plugin.protoeditor (223.8214.6)
    dev.polek.adbwifi (1.2.5)
    de.ohmesoftware.parcelablegenerator (0.7.1)

这是我现在使用的 as版本，编译项目 提示
The project is using an incompatible version (AGP 8.3.0-alpha07) of the Android Gradle plugin. Latest supported version is AGP 8.1.3
能否降低 AGP的版本？

**Comment by miaowmiaow** [comment]
这是我的疏忽导致的。
master分支将保证最新稳定版 Android Studio 运行。
dev分支需要最新预览版本 Android Studio 运行，以保证支持compose的新特性。
请重新拉去代码。
