### ISSUE TITLE
请求另外一个url地址的数据应该怎么弄？

### ISSUE THREAD

**Issue by txxxtxx** [miaowmiaow/fragmject#3]

**Comment by miaowmiaow** [comment]
app模块中的App文件设置

`    private fun initSimpleHttp() {
        SimpleHttp.setBaseUrl("https://www.wanandroid.com/")
    }
`

**Comment by marren06** [comment]
> app模块中的App文件设置
> 
> ` private fun initSimpleHttp() { SimpleHttp.setBaseUrl("https://www.wanandroid.com/") }
他的意思是说接口有多个BaseUrl 不是固定一个

**Comment by miaowmiaow** [comment]
> 
你可以通过代码，如下进行请求：
val request = HttpRequest("https://www.baidu.com")
val response = get<HttpResponse>(request)

如果以上方式不能满足需求，请创建多个Retrofit。

**Comment by miaowmiaow** [comment]
> > app模块中的App文件设置
> > ` private fun initSimpleHttp() { SimpleHttp.setBaseUrl("https://www.wanandroid.com/") }
> > 他的意思是说接口有多个BaseUrl 不是固定一个

你可以通过代码，如下进行请求：
val request = HttpRequest("https://www.baidu.com/")
val response = get(request)

如果以上方式不能满足需求，请创建多个Retrofit。
