### ISSUE TITLE
寻求课程合作

### ISSUE THREAD

**Issue by specialzxw** [miaowmiaow/fragmject#5]
hi，刚刚偶然看到您分享的这个项目，我们对这个项目很感兴趣，看得出您得 kotlin 十分了解，我们想邀请您结合此项目与我们进行课程合作，制作相关的实战入门课程，将您的技术经验分享给更多人学习，但是 github 上没有留下您的联系方式，如果您对我们的提议感兴趣的话，可以在这里留下您的邮箱或微信，方便我们与您建立联系；或者直接联系我们的官方合作微信号 “shiyanloukecheng”，期待您的回复。

**Comment by miaowmiaow** [comment]
好的，如果有需要，后续我将联系你们。
