### ISSUE TITLE
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.2 or newer.

### ISSUE THREAD

**Issue by ThirdPrince** [miaowmiaow/fragmject#6]
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.2 or newer.

**Comment by miaowmiaow** [comment]
if you use Android Studio please updates version 4.2 or newer. 
if you use IDEA  [please click here](https://youtrack.jetbrains.com/issue/IDEA-264255).
I hope you will use Google.

**Comment by miaowmiaow** [comment]
if you use Android Studio please updates version 4.2 or newer.
if you use IDEA please click here.
I hope you will use Google.
I'll close ISS in a day.

**Comment by miaowmiaow** [comment]
if you use Android Studio please updates version 4.2 or newer.
if you use IDEA [please click here](https://youtrack.jetbrains.com/issue/IDEA-264255).
I hope you will use Google.
I'll close issues in a day.

**Comment by ThirdPrince** [comment]
OK
