### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by jiantao88** [miaowmiaow/fragmject#7]
Task :library-base:kaptDebugKotlin FAILED
Execution failed for task ':library-base:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)

**Comment by miaowmiaow** [comment]
我需要更多的日志才能帮你排查问题。
这是我搜索到类似问题的解决方案，你可以[点击这里](https://www.jianshu.com/p/a2ea408de419)参考下。
如果问题已经解决请给我回复以便于关闭这个issues。

**Comment by jiantao88** [comment]
应该是room库 再Mac M1 电脑兼容问题，升级到2.4.0以上就可以，但是compileSdkVersion要设置为31

https://stackoverflow.com/questions/68884589/caused-by-java-lang-exception-no-native-library-is-found-for-os-name-mac-and-o
