### ISSUE TITLE
这里的代码是不是写错了？

### ISSUE THREAD

**Issue by guozhiqiang123** [miaowmiaow/fragmject#8]
![Screenshot_20220313_095635](https://user-images.githubusercontent.com/20378988/158041591-a35430b9-6e53-4fd4-abfc-210e144756d0.png)

不应该是webViewCache.first()吗？

**Comment by miaowmiaow** [comment]
webViewCache.removeFirst()，删除列表中第一个元素，并返回该删除的元素。
这么写的原因是当你有多个页面使用到WebView时不会报以下错误：
The specified child already has a parent. You must call removeView() on the child's parent first.
