### ISSUE TITLE
编译报错 

### ISSUE THREAD

**Issue by wohelu666** [miaowmiaow/fragmject#9]
编译报错， as 版本：4.0.0 gradle version:6.1.1
![image](https://user-images.githubusercontent.com/48713628/162654000-e2103b95-88f0-4a71-aeac-d03a0f42b3f9.png)

**Comment by miaowmiaow** [comment]
as请升级到4.2.2

**Comment by wohelu666** [comment]
这边升级到7.1.2的版本也是不行的，报错一样。
![image](https://user-images.githubusercontent.com/48713628/162859530-03b9add1-d097-4e80-8bc3-0acf4b6aa8d2.png)

**Comment by miaowmiaow** [comment]
> 这边升级到7.1.2的版本也是不行的，报错一样。 ![image](https://user-images.githubusercontent.com/48713628/162859530-03b9add1-d097-4e80-8bc3-0acf4b6aa8d2.png)

抱歉比较晚看到你的问题，运行环境确实是让人很头疼的问题，最简单的方法是使用项目相同环境。
fragmject/gradle/wrapper/gradle-wrapper.properties
fragmject/build.gradle
